name: publish

on:
  push:
  workflow_dispatch:

jobs:
  # https://dart.dev/tools/pub/automated-publishing
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v3
      - uses: ./
